name: Waste Free Me
favicon: null
layout_spectrum: 0.5578271592967212
typography_spectrum: 0.4210862456820905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d8d7'
    - '#9eacb2'
    - '#3e415b'
    - '#6b7d8f'
    - '#12141b'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.18754901620559394
purpose: []
